config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "cards#index"

  resources :cards do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :comments

  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render :new
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render :edit
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to root_path
  end

  private

  def card_params
    params.require(:card).permit(:title, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @card = Card.find(params[:card_id])
    @comment = @card.comments.create(comment_params)
    redirect_to card_path(@card)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/cards/_comments.html.erb
    <section class="mt-5">
      <h2>Comments</h2>
      <% @card.comments.each do |comment| %>
        <p class="commenter"><%= comment.commenter %>:</p>
        <p class="comment"><%= comment.body %></p>
      <% end %>
    <section>

app/views/cards/_form.html.erb
<%= form_with model: @card do |form| %>
  <div>
    <%= form.label :title, :class => 'form-label' %><br>
    <%= form.text_field :title, :class => 'form-input' %>
    <% @card.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :description, :class => 'form-label mt-2' %><br>
    <%= form.text_area :description, :class => 'form-input' %>
    <% @card.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Submit", :class => 'btn mt-4' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<section class="container py-5">
  <h1>Edit Card</h1>
  <%= render "form", card: @card %>
</section>

app/views/cards/index.html.erb
<section class="container-fluid section-hero">
  <div class="row py-5">
    <div class="col-md-10 offset-md-1 text-center">
      <h1 class="mb-4">Happy Wins</h1>
      <p>Hey budding Rails developer! You're awesome and doing a great job!</p>
      <p>The learning journey has its fill of mountains and valleys. While you are here, why not share a win, something fun you've learned, or a favorite resource.</p>
      <%= link_to "Add Note", new_card_path, class: "btn" %>
    </div>
  </div>
</section>

<section class="container-fluid py-5 section-cards grow-2">
  <div class="container">
    <div class="row cards-row g-4">
        <% @cards.each do |card| %>
        <div class="col">
          <div class="card card-index-page">
            <div class="card-body">
            <p class="card-title"><%= link_to card.title, card %></p>
            <p class="card-text"><%= card.description%></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
  </div>
</section>

app/views/cards/new.html.erb
<section class="container py-5">
  <h1>Share Something Fun</h1>
  <%= render "form", card: @card %>
</section>

app/views/cards/show.html.erb
<section class="container py-5">
  <div class="card card-full-details">
    <div class="card-body">
      <h1 class="card-title"><%= @card.title %></h1>
      <p class="card-text"><%= @card.description %><p>
    </div>
  </div>
  <%= link_to "Edit this Card", edit_card_path, class: "btn me-2" %>
  <%= link_to "Delete this Card", card_path(@card), class: "btn", method: :delete, data: { confirm: "Are you sure?" } %>

  <% if @card.comments.present? %>
    <%= render "comments", card: @card %>
  <% end %>

  <section class="mt-5">
  <h2>Add Your Own Comment</h2>
  <%= form_with model: [ @card, @card.comments.build ] do |form| %>
    <p>
      <%= form.label :body, "Comment", :class => 'form-label' %><br>
      <%= form.text_area :body, :class => 'form-input' %>
    </p>
      <p>
      <%= form.label :commenter, "Your Name", :class => 'form-label' %><br>
      <%= form.text_field :commenter, :class => 'form-input' %>
    </p>
    <p>
      <%= form.submit "Add Comment", :class => 'btn' %>
    </p>
  <% end %>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy Wins</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('happy-wins.png') %>
  </head>
  
  <body class="d-flex flex-column">
  <nav>
    <%= link_to "Happy Wins", root_path, class: "nav-home" %>
    <%= link_to "Add Note", new_card_path, class: "btn" %>
  </nav>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>